* Back alley ribs
Original recipe from https://munchies.vice.com/recipes/back-alley-ribs
** Ingredients
- 10 lbs. pork side ribs
- water
- salt
- for the pomegranate molasses barbecue sauce:
  - 2 onions
  - 5 jalapeños
  - 4 cloves garlic
  - 1 knob of ginger
  - 4 tablespoons canola oil
  - 2 tablespoons cayenne pepper
  - 2 tablespoons garlic powder
  - 2 tablespoons onion powder
  - 2 tablespoons mace
  - 1 tablespoon ground clove
  - 2 tablespoons ground coriander
  - 3 tablespoons smoked paprika
  - 3 tablespoons Korean chili flakes
  - 10 pomegranates
  - 4 tablespoons molasses
  - 4 tablespoons maple syrup
  - 4 tablespoons apple cider vinegar
  - 2 cups water
- for the dukkah:
  - white sesame seeds
  - black sesame seeds
  - pistachios
  - fennel seed
  - sunflower seeds
  - pumpkin seeds
- for serving:
  - limes
  - pomegranates
  - cilantro
** Instructions
1. To cook the ribs, place ribs in a pot with cold, heavily salted water (make
   it taste like the ocean) and cover. Bring to a boil, then reduce to medium
   heat and let simmer. Skim the scum from the top. Cook until tender, about an
   hour and half.

2. To make the pomegranate molasses barbecue sauce, heat the canola oil in a
   saucepan over medium heat. Chop onions, garlic, jalapeño, and ginger and cook
   in the oil until golden brown. Add the cayenne, garlic powder, onion powder,
   mace, ground clove, ground coriander, smoked paprika, and Korean chili
   flakes. Add all of the seeds and juice from the pomegranates, then add the
   molasses, maple syrup, apple cider vinegar, and water. Bring to a boil, then
   simmer for 1 hour. When cool, blend in a blender until smooth.

3. For the dukkah, take all the seeds and place in a blender. Blitz on pulse
   until crumbly. Place in a bowl and set aside.

4. Chop the parsley and cilantro and place in a bowl.

5. Heat your grill up really, really hot! Place ribs on grill and start basting
   with the barbecue sauce. You are gonna have to move quick here, so don’t
   crowd the grill. Glaze ribs, flip ribs, glaze ribs, flip ribs, until nice and
   sticky and charred. Repeat until all ribs are cooked

6. Place ribs on a nice cutting board and give them a final glaze of the
   barbecue sauce. Then sprinkle with the fresh-cut herbs and the dukkah. Slice
   the ribs into individual ribs for your guests. Add some lime wedges for a
   fresh hit of acid, squeeze some pomegranate juice and seeds on them, and
   you're done. World peace!
