* Erdäpfel Radieschen Salat mit Matjes

** Zutaten
- 1 kg	kleine Erdäpfel
- 1 Bund	Schnittlauch
- 1 Handvoll	Petersilienblätter
- 250 g	Joghurt
- 4 EL	Kräuteressig
- 4 EL	Rapsöl
- 1 Bund	Jungzwiebeln
- 0,5 Salatgurke
- 0,5 Bund Radieschen
- 150 g Matjes oder Räucherlachs
- Salz, schwarzer Pfeffer aus der Mühle
 
** Zubereitung

Erdäpfel putzen und ca. 20 Minuten gar kochen. Abgießen, kalt abschrecken, kurz abkühlen lassen, schälen und weiter abkühlen lassen.
Währenddessen für das Dressing den Schnittlauch in feine Röllchen schneiden, Petersilie fein hacken und beides mit Joghurt, Essig, Öl, 4 EL Wasser, Salz und Pfeffer verquirlen.

Erdäpfel der Länge nach halbieren, mit dem Dressing verrühren und 20 Minuten ziehen lassen.

Währenddessen die Jungzwiebeln putzen und in feine Röllchen schneiden. Gurke putzen, der Länge nach halbieren und der Breite nach in dünne Scheiben schneiden. Radieschen putzen und in feine Scheiben schneiden oder hobeln.

Jungzwiebeln, Gurke und Radieschen unter den Erdäpfelsalat mischen und mit Salz und Pfeffer abschmecken. Räucherlachs in grobe Stücke zupfen.

Räucherlachs unter den Salat mischen und servieren.

* :Kartoffeln:Fisch:Salat:

* Quelle

Originalrezept von [[https://www.billa.at/Frischgekocht_ONLINE/Frisch_Gekocht/Rezepte/Rezept_Detail/Rezept_Detail/FgContent.aspx?Rezept=24457&Erdaepfel-Radieschen-Salat_mit_Raeucherlachs][Billa]].
