* Momofuku pulled pork
This is the master recipe for pork shoulder at Momofuku—the stuff in the buns,
the ramen, this is it. It’s embarrassingly simple. The idea is to add pure,
clean pork flavor to a more complicated, layered dish. It takes at least a day
and a half, ’cause there’s a lot of necessary chilling between steps, so plan in
advance, or no pork for you.

INGREDIENTS

3 or more lbs boneless pork shoulder
1 T + 1 t salt per pound of pork
1 T + 1 t sugar per pound of pork
+ black pepper

1. Season the shoulder with the salt and sugar. Hit it with a couple turns of
   freshly ground black pepper. Let it sit overnight, covered, in the fridge.
2. Throw the seasoned shoulder in a roasting pan. Cook, uncovered, in a 250°F
   oven for 6 hours. After 3 hours, start basting it occasionally with the
   rendered fat and juices that have accumulated in the pan.
3. After 6 hours, take it out of the oven and let it take a breather on the
   counter for at least half an hour. Then savage it with two forks, turning it
   into pulled pork. Use at once or pack it up and put it back in the fridge.
   This pulled pork is as good in ramen as it is tossed with some barbecue sauce
   and stuck between a couple buns, so don’t be shy about making a bunch of it.
